Build step refactor
StochSS/GillesPy2 pull request #520
Opened 2021-06-02 14:27 UTC by ethangreen-dev

This PR contains a major overhaul to the C++ build infrastructure. 

Additions:
+ `make.py` - A `make` wrapper to enable Python-level control over the compilation process.
+ `build_engine.py` - A public-facing class which validates target input/output directories, automates `make` compilation, and cleans up once complete.
+ `template_gen.py` - Functions to enable writes to the new template definitions format.

+ `c_decoder.py` - An abstract class that defines the behavior of an simulation decoder. This file also contains a basic decoder, which is used to parse a C++ solver output.
+ `c_solver.py` - A superclass containing several helper functions pertaining to argument validation, solver compilation, and solver execution.

Notes:
- Cached compilation is implemented but is not yet "hooked up".
- A `cache_enabled` variable has been set to `False` in the top-level `__init__.py` file. Cache cannot be enabled yet, so this should not be modified.
- `BuildEngine` and `SimDecoder` tests have been added.

2021-06-02 17:21 UTC, jtcooper10 commented on gillespy2/solvers/utilities/buildutils.py
> +from typing import OrderedDict
This file is duplicated in `template_gen.py`. Should be able to just remove this one

2021-06-02 17:22 UTC, jtcooper10 commented on gillespy2/solvers/cpp/c_decoder.py
> +        """
Empty docsting

2021-06-08 14:46 UTC, BryanRumsey commented on gillespy2/solvers/cpp/__init__.py
> +from gillespy2.core import logging
Should import `log` not `logging`

2021-06-08 18:10 UTC, BryanRumsey requested changes

2021-06-08 19:09 UTC, BryanRumsey approved these changes

2021-06-11 15:57 UTC, seanebum approved these changes

2021-06-11 16:45 UTC, merged