Hybrid Rate Rules
StochSS/GillesPy2 pull request #583
Opened 2021-07-21 20:35 UTC by jtcooper10

2021-09-14 18:54 UTC, seanebum approved these changes

2021-09-21 13:50 UTC, BryanRumsey requested changes

2021-09-21 20:17 UTC, BryanRumsey commented on gillespy2/solvers/cpp/build/template_gen.py
> +            if isinstance(rate_rule.variable, Species) \
This is resolved in the latest commit with a check for parameters as rate rule variables.
A Simulation Error will be raised.

2021-09-21 20:17 UTC, BryanRumsey commented on gillespy2/solvers/cpp/build/template_gen.py
> +            spec_rr = model.rate_rules.get(species)
Resolved in the above conversation.

2021-09-21 20:18 UTC, BryanRumsey approved these changes

2021-09-23 16:21 UTC, merged