Example rework
StochSS/GillesPy2 pull request #737
Opened 2022-02-28 22:11 UTC by JoshuaFisherC

Extensive update to entire examples folder to make it more beginner friendly. Also updated deprecated functions in results.py to correctly display a deprecation warning.

2022-03-08 19:17 UTC, BryanRumsey requested changes
Remove all un-used solver imports and commented code

Dask worker space directory shouldn't be pushed up to github.

[GillesPy2_photosynthesis_ex.pdf](https://github.com/StochSS/GillesPy2/pull/737/files#diff-3f807bce749ce9d0e7eb1545690251726c09a7a8ca0d7414c13c9a39cb82e0f2) contians an image with a simulation error.

[CLE_examples_convergence.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-87c109db948bb574058c10cfced25f4ed9b410218a4435314f6b997e4c9b93d3)
- Replace `solver=SSACSolver` with `algorithm=SSA`
- Replace `solver=ODECSolver` with `algorithm=ODE`

[Events.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-66868894fa9e3c6eda6b2f1bdaf2ed967c8b89fd0d75a0400e01e8088457d463)
- Reference to `BasicTauHybridSolver` in code block 1.
- Update the note in code block 1 to include `TauHybridCSolver` as a viable solver for events.

[Run GillesPy2 Simulations in Parallel.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-990a83847cbc6ace9163a6ce8a9450119d2abdbbfd067626a7e4b223da9572d1)
- Notebook shouldn't contain a port warning.
- Replace deprecated `plot_std_dev_range` with `plot_mean_stdev`.

[SBML_Import_Test.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-43565e78dc36edebfe5713087f56eda6a75d20e03a1d0024e3277aeee9c4c6bf)
- Download link for sbml file is broken.  The correct link is `https://www.ebi.ac.uk/biomodels/model/download/BIOMD0000000028.2?filename=BIOMD0000000028_url.xml`

[Variable_SSA_C_Example.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-2f97bea2d0eae5c6fb020db2e00915d077a54e018d6c0e3676b4ca933bb37f13)
- `TauHybridCSolver` is missing from the notebook docs.
- The final plot cell contains a simulation error.
                               
[hybrid_continuous_species.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-05ffbf93d10ace31e047e4c531b2a6ac0c75ec59bfa6daaa23bffb4631abd8e7)
- Reference to `Basic Tau Hybrid Solver` in notebook header.
- Plot contains a simulation error.
       
[DataVisualization.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-4512d0a40074cef86f489311f90c2c9d5ef02faf65b42b5df9bde2b92b214b8e)
- Remove deprecated function call `plot_std_dev_range`.
- Remove deprecated function call `plotplotly_std_dev_range`.
                    
[GeneticToggleSwitch.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-187d82ccc883651bf082f894df88634ae410c5e472a135da4bdd2900813748ae)
- Remove the incorrect comment:
```
#Default solver for model.run() is the VariableSSACSolver. For more information,
# checkout /examples/AdvancedFeatures/Variable_SSA_C_Example.ipynb
```

[Opioid_Model.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-880dc9ab487fcb8ff714451b6ef56979b60704eede4a05c0b2cd9a47d1198da5)
- Reference to `Basic Tau Leaping` in notebook header.
- Reference to deprecated `show_labels` in notebook docs for `Run Model and plot`.

[Oregonator.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-c91101c5ceb6db988b80851823d9c8cb1097900a085aaaa0bf43c66381487f50)
- Replace `solver=SSACSolver` with `algorithm=SSA`.
- Replace `solver=ODESolver` with `algorithm=ODE`.

[TauSolverRunTimeComparison.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-f5d6f8d5fdbd3cfd990e318f22d86f6cfb6e24fa9c9ebf33e07a33f47d027744)
- initial_condition of `V` should be set to `n` in for loop and should work with python and c solvers.
- Instantiate `timing_data` as an empty dict.

[TauSolverRunTimeComparison.py](https://github.com/StochSS/GillesPy2/blob/db05093ec4931a9aadbf57a983527be81bee427b/examples/Models/ExtraModels/SpeedComparisons/TauSolverRunTimeComparison.py)
- Needs to be updated to match the notebook or removed.

[Michaelis-Menten.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-63476854e725f204dd25407f643f2b6b4b92c63b10a7f6ca01bf0a665f404e6f)
- Reference to deprecated `show_labels` in notebook docs for `Run Model and plot`.

[VilarOscillator.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-6a3bb3393362d01f81a244d114a069a92ac0aa73acca7d24502aac05d0defe13)
- Reference to deprecated `show_labels` in notebook docs for `Run Model and plot`.

[ResultsManagement.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-fb56c484c56c56607d8888c5f7c4fe464f8205d949613e8816da26c0296ca8b1)
- Remove warnings import

[StartHere.ipynb](https://github.com/StochSS/GillesPy2/pull/737/files#diff-e6c3aa613ced4aa1843c7edf5ad247e776a498c15afe5d9eb1d4c35b07d59708)
- Remove cell with solver imports

2022-03-15 14:28 UTC, BryanRumsey requested changes

2022-03-16 20:01 UTC, BryanRumsey approved these changes
Everything looks good to go

2022-03-24 18:40 UTC, briandrawert approved these changes

2022-03-24 19:35 UTC, merged