Solver doc fix
StochSS/GillesPy2 pull request #817
Opened 2022-05-29 00:29 UTC by JoshuaFisherC

Updated and fleshed out numpy solver documentation.

2022-05-31 13:12 UTC, BryanRumsey commented on gillespy2/solvers/numpy/CLE_solver.py
> +        :returns: a list of each trajectory simulated.
solver run functions always return result objects not lists.  Also missing the rtype tag for the return type

2022-05-31 13:24 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ode_solver.py
>          :param model: gillespy2.model class object
Add `(deprecated)` to the description of the model are to indicate that this arg is deprecated

2022-05-31 13:29 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ode_solver.py
> +        :param resume: Result of a previously run simulation, to be resumed
missing type tag for resume arg

2022-05-31 13:31 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ode_solver.py
> +        :returns: a list of each trajectory simulated.
solver run functions always return result objects not lists. Also missing the rtype tag for the return type

2022-05-31 13:36 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ssa_solver.py
> +        :type t: int
`t` can be an int or float

2022-05-31 13:41 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_hybrid_solver.py
>          :type live_output_options:  str
`live_output_options` is a dict not str

2022-05-31 13:42 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_hybrid_solver.py
> +        :returns: a list of each trajectory simulated.
solver run functions always return result objects not lists. Also missing the rtype tag for the return type

2022-05-31 13:44 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +        :param resume: Result of a previously run simulation, to be resumed
missing type tag for resume arg

2022-05-31 13:45 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +        :returns: a list of each trajectory simulated.
solver run functions always return result objects not lists. Also missing the rtype tag for the return type

2022-06-19 14:30 UTC, BryanRumsey requested changes

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/cpp/tau_leaping_c_solver.py
> +        :param number_of_trajectories: Should be 1. This is deterministic and will always have same results
This is incorrect

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/CLE_solver.py
> +    :param model: The model on which the solver will operate. (Deprecated)
Model is not deprecated in the init function

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/CLE_solver.py
> +    :type model: GillesPy2.model
lowercase 'G' and 'P' for types

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ode_solver.py
> +    :param model: The model on which the solver will operate. (Deprecated)
Model is not deprecated in the init function

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ode_solver.py
> +    :type model: GillesPy2.model
lowercase 'G' and 'P' in types

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ssa_solver.py
> +    :param model: The model on which the solver will operate. (Deprecated)
Model is not deprecated in the init function

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/ssa_solver.py
> +    :type model: GillesPy2.model
lowercase 'G' and 'P' in types

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_hybrid_solver.py
> +    :param model: The model on which the solver will operate. (Deprecated)
Model is not deprecated in the init function

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_hybrid_solver.py
> +    :type model: GillesPy2.model
lowercase 'G' and 'P' in types

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +    :param model: The model on which the solver will operate. (Deprecated)
Model is not deprecated in the init function

2022-06-19 14:30 UTC, BryanRumsey commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +    :type model: GillesPy2.model
lowercase 'G' and 'P' in types

2022-06-28 11:54 UTC, BryanRumsey approved these changes

2022-06-29 20:37 UTC, mdip226 reviewed
Just minor changes so that there is a uniform format throughout. Nothing major, looks good! Some of my comments are just me thinking and may not require a change at all.

2022-06-29 20:37 UTC, mdip226 commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +        :param resume: Result of a previously run simulation, to be resumed
.

2022-06-29 20:37 UTC, mdip226 commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +        :returns: A result object containing the results of the simulation
.

2022-06-29 20:37 UTC, mdip226 commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +        :param live_output_options: Contains options for live_output. By default {"interval":1}. "interval"
newline tab like the others

2022-06-29 20:37 UTC, mdip226 commented on gillespy2/solvers/numpy/CLE_solver.py
> +        :param live_output_options: Contains options for live_output. By default {"interval":1}. "interval"
newline tab like the others

2022-07-14 20:29 UTC, mdip226 commented on gillespy2/solvers/numpy/ssa_solver.py
>          Run the SSA algorithm using a NumPy for storing the data in arrays and generating the timeline.
I think you meant to say something like 'Run the SSA algorithm. Uses a NumPy array to store results and for generating the timeline.' Just missed a word after NumPy.

2022-07-14 20:31 UTC, mdip226 commented on gillespy2/solvers/cpp/tau_leaping_c_solver.py
> +    A Tau Leaping solver for GillesPy2 models.  This solver uses an algorithm calculates
algorithm 'that' calculates

2022-07-14 20:33 UTC, mdip226 commented on gillespy2/solvers/numpy/tau_leaping_solver.py
> +    A Tau Leaping solver for GillesPy2 models.  This solver uses an algorithm calculates
algorithm 'that'

2022-07-16 15:23 UTC, BryanRumsey requested changes

2022-07-16 15:23 UTC, BryanRumsey commented on gillespy2/solvers/cpp/ode_c_solver.py
> +    Uses integrators from scipy.integrate.ode to perform calculations used to produce solutions.
Is this correct? I believe we use Sundials for the C++ ode solvers

2022-08-09 17:37 UTC, briandrawert approved these changes

2022-08-09 17:38 UTC, merged