Replace Makefile build back end with SConstruct
StochSS/GillesPy2 pull request #879
Opened 2022-10-09 16:23 UTC by jtcooper10

2022-10-12 15:26 UTC, BryanRumsey requested changes
Need to add copyright block to all new files.

2022-10-12 15:26 UTC, BryanRumsey commented on gillespy2/solvers/cpp/build/build_engine.py
>              self.makefile = self.cpp_dir.joinpath("Makefile")
Remove lines 38 - 41.
Line 42 re-assigns self.makefile.

2022-10-13 19:20 UTC, briandrawert approved these changes

2022-10-17 00:12 UTC, mdip226 commented
Good luck reading this. It's definitely having a permission error creating a tempfile. (Line 9) I think that makes sense, because it looks like it's trying to make it in C:/WINDOWS which I assume is not allowed.
[out.txt](https://github.com/StochSS/GillesPy2/files/9795986/out.txt)

2022-10-17 00:14 UTC, mdip226 commented
Here's the important part:
`"name": "SimulationError",
	"message": "<class 'gillespy2.solvers.cpp.ssa_c_solver.SSACSolver'> is not a valid solver.  Reason Given: Error encountered during execution of Makefile target: 'ssa'.\nReturn code: 2- stdout: scons: Entering directory `C:\\Users\\mdip2\\AppData\\Local\\Temp\\gillespy2_build_695gskgr'\r\nscons: Reading SConscript files ...\r\nscons: done reading SConscript files.\r\nscons: Building targets ...\r\ng++ -o gillespy2_obj\\arg_parser.o -c -std=c++14 -IC:\\Users\\mdip2\\Projects\\GillesPy2\\gillespy2\\solvers\\cpp\\c_base -Igillespy2_template -IC:\\Users\\mdip2\\Projects\\GillesPy2\\gillespy2\\solvers\\cpp\\c_base\\Sundials\\include -IC:\\Users\\mdip2\\Projects\\GillesPy2\\gillespy2\\solvers\\cpp\\c_base\\Tau C:\\Users\\mdip2\\Projects\\GillesPy2\\gillespy2\\solvers\\cpp\\c_base\\arg_parser.cpp\r\nscons: building terminated because of errors.\r\n\n- stderr: Cannot create temporary file in C:\\WINDOWS\\: Permission denied\r\nscons: *** [gillespy2_obj\\arg_parser.o] Error 3\r\n\n- make_cmd: ['C:\\\\Users\\\\mdip2\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\\\python.exe', '-m', 'SCons', '-CC:\\\\Users\\\\mdip2\\\\AppData\\\\Local\\\\Temp\\\\gillespy2_build_695gskgr', '-fC:\\\\Users\\\\mdip2\\\\Projects\\\\GillesPy2\\\\gillespy2\\\\solvers\\\\cpp\\\\build\\\\SConstruct', 'CBASE_DIR=C:\\\\Users\\\\mdip2\\\\Projects\\\\GillesPy2\\\\gillespy2\\\\solvers\\\\cpp\\\\c_base', 'OBJ_DIR=C:\\\\Users\\\\mdip2\\\\AppData\\\\Local\\\\Temp\\\\gillespy2_build_695gskgr\\\\gillespy2_obj', 'TEMPLATE_DIR=C:\\\\Users\\\\mdip2\\\\AppData\\\\Local\\\\Temp\\\\gillespy2_build_695gskgr\\\\gillespy2_template', 'SOLVER=ssa', 'OUTPUT_FILE=C:\\\\Users\\\\mdip2\\\\AppData\\\\Local\\\\Temp\\\\gillespy2_build_695gskgr\\\\GillesPy2_Simulation.exe']\n- os.listdir(C:\\Users\\mdip2\\Projects\\GillesPy2\\gillespy2\\solvers\\cpp\\c_base\\template): ['template.cpp', 'template.h', 'template_defaults.h', 'template_definitions.h', 'template_opts.h', 'template_params.h']\n."`

2022-10-17 00:22 UTC, mdip226 requested changes
See my comments

2022-10-17 13:47 UTC, mdip226 commented
This was when I was trying to run StartHere.ipynb (not compute) on windows,
by bad I should have included more info. Does the scons python package
require the windows executable scons.exe to be installed?

On Mon, Oct 17, 2022, 08:52 Joshua Cooper ***@***.***> wrote:

> Good luck reading this. It's definitely having a permission error creating
> a tempfile. I think that makes sense, because it looks like it's trying to
> make it in C:/WINDOWS which I assume is not allowed. The only thing I can
> think of is that I did not use venv to install scons, so it thinks that it
> has administrator access. Also I'm using mingw64 if that matters.
>
> I am not sure what \r\scons is.
>
> out.txt <https://github.com/StochSS/GillesPy2/files/9795986/out.txt>
>
> This doesn't really tell me anything, what's the context? This looks like
> it's JSONify output, I'm guessing this is related to compute?
>
> And the \\r\\nscons is just a Win32-style line feed followed before the
> scons command
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/StochSS/GillesPy2/pull/879#issuecomment-1280812864>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMIVBA7YOEDUOZKOCCOHOHLWDVDYXANCNFSM6AAAAAARAYDCTU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-17 13:48 UTC, mdip226 commented
Its the error message produced by Jupyter, opened in a text editor cuz the
error message was big

On Mon, Oct 17, 2022, 09:46 Matt Dippel ***@***.***> wrote:

> This was when I was trying to run StartHere.ipynb (not compute) on
> windows, by bad I should have included more info. Does the scons python
> package require the windows executable scons.exe to be installed?
>
> On Mon, Oct 17, 2022, 08:52 Joshua Cooper ***@***.***>
> wrote:
>
>> Good luck reading this. It's definitely having a permission error
>> creating a tempfile. I think that makes sense, because it looks like it's
>> trying to make it in C:/WINDOWS which I assume is not allowed. The only
>> thing I can think of is that I did not use venv to install scons, so it
>> thinks that it has administrator access. Also I'm using mingw64 if that
>> matters.
>>
>> I am not sure what \r\scons is.
>>
>> out.txt <https://github.com/StochSS/GillesPy2/files/9795986/out.txt>
>>
>> This doesn't really tell me anything, what's the context? This looks like
>> it's JSONify output, I'm guessing this is related to compute?
>>
>> And the \\r\\nscons is just a Win32-style line feed followed before the
>> scons command
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/StochSS/GillesPy2/pull/879#issuecomment-1280812864>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AMIVBA7YOEDUOZKOCCOHOHLWDVDYXANCNFSM6AAAAAARAYDCTU>
>> .
>> You are receiving this because your review was requested.Message ID:
>> ***@***.***>
>>
>

2022-10-17 14:20 UTC, mdip226 commented
It was a hasty attempt that involved
1. cloning Gillespie repo
2. Installing mingw along with g++, make (I actually had a little trouble locating the correct make and I'm still not 100% sure its the correct one but I think it is. Both commands seem to run from cmd but I never tested them farther than knowing they are in the path.
3. pip install scons
4. Running starthere.ipynb in vscode

2022-11-16 04:51 UTC, BryanRumsey requested changes
Integration with StochSS fails on staging and local with Apple M1 chip.

## Error from Tests
```
ERROR: test_ode_c_solver (test_gillespy2.TestGillesPy2Dependency) (model='Brusselator')
Check if the test_models run with the ODECSolver.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/gillespy2/core/model.py", line 1282, in run
    return solver.run(t=t, increment=increment, timeout=timeout, **solver_args)
  File "/opt/conda/lib/python3.8/site-packages/gillespy2/solvers/cpp/ode_c_solver.py", line 177, in run
    sim_status = self._run(sim_exec, args, decoder, timeout, display_args)
  File "/opt/conda/lib/python3.8/site-packages/gillespy2/solvers/cpp/c_solver.py", line 217, in _run
    with subprocess.Popen(sim_args, stdout=subprocess.PIPE, **platform_args) as simulation:
  File "/opt/conda/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gillespy2_build_t5ngffyr/GillesPy2_Simulation.out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/stochss/stochss/tests/test_gillespy2.py", line 109, in test_ode_c_solver
    test_model.run(solver=test_solver)
  File "/opt/conda/lib/python3.8/site-packages/gillespy2/core/model.py", line 1284, in run
    raise SimulationError(
gillespy2.core.gillespyError.SimulationError: argument 'solver=<gillespy2.solvers.cpp.ode_c_solver.ODECSolver object at 0x7f5c92f72250>' to run() failed.  Reason Given: [Errno 2] No such file or directory: '/tmp/gillespy2_build_t5ngffyr/GillesPy2_Simulation.out'
```

## Error from Job on staging
```
2022-11-16 04:51:15,882 - GillesPy2 - ERROR - Job errors: argument 'solver=' to run() failed. Reason Given: [Errno 2] No such file or directory: '/tmp/gillespy2_build__cbm2cey/GillesPy2_Simulation.out'
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/gillespy2/core/model.py", line 1282, in run
return solver.run(t=t, increment=increment, timeout=timeout, **solver_args)
File "/opt/conda/lib/python3.8/site-packages/gillespy2/solvers/cpp/ssa_c_solver.py", line 166, in run
sim_status = self._run(sim_exec, args, decoder, timeout, display_args)
File "/opt/conda/lib/python3.8/site-packages/gillespy2/solvers/cpp/c_solver.py", line 217, in _run
with subprocess.Popen(sim_args, stdout=subprocess.PIPE, **platform_args) as simulation:
File "/opt/conda/lib/python3.8/subprocess.py", line 854, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/opt/conda/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/gillespy2_build__cbm2cey/GillesPy2_Simulation.out'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/stochss/stochss/handlers/util/scripts/start_job.py", line 118, in
job.run(verbose=args.verbose)
File "/stochss/stochss/handlers/util/ensemble_simulation.py", line 125, in run
results = self.g_model.run(number_of_trajectories=1 if is_ode else 100)
File "/opt/conda/lib/python3.8/site-packages/gillespy2/core/model.py", line 1284, in run
raise SimulationError(
gillespy2.core.gillespyError.SimulationError: argument 'solver=' to run() failed. Reason Given: [Errno 2] No such file or directory: '/tmp/gillespy2_build__cbm2cey/GillesPy2_Simulation.out'
```

2023-01-04 19:15 UTC, merged