Fixes #874 for TauHybridSolver
StochSS/GillesPy2 pull request #891
Opened 2022-12-05 23:21 UTC by briandrawert

2022-12-14 14:30 UTC, BryanRumsey requested changes
Something is causing inconsistent results with the Opioid model.
## Test Code
```
t_results1 = model.run(solver=gillespy2.TauHybridSolver)
t_results1.plot(
    title=f"{model.name}: {t_results1.solver_name}",
    included_species_list=['Susceptibles','Prescribed_Users','Addicted','Rehab']
)
t_results2 = model.run(solver=gillespy2.TauHybridCSolver)
t_results2.plot(
    title=f"{model.name}: {t_results2.solver_name}",
    included_species_list=['Susceptibles','Prescribed_Users','Addicted','Rehab']
)
```
## Test Results
![image](https://user-images.githubusercontent.com/44621966/207621950-4081eab8-2e53-4712-a624-a14d865b77f2.png)
![image](https://user-images.githubusercontent.com/44621966/207622010-47b84cb8-8fe2-4a56-9cc8-5ca54e30a4b2.png)

## Results from Notebook
![image](https://user-images.githubusercontent.com/44621966/207622505-48adcccb-66e3-46c1-8bb8-22a4e3bd4528.png)

2022-12-20 05:58 UTC, briandrawert commented
The Opioid model is fixed in PR #903

2022-12-22 14:33 UTC, jtcooper10 approved these changes

2022-12-22 14:42 UTC, BryanRumsey approved these changes

2022-12-22 19:19 UTC, seanebum approved these changes

2022-12-22 19:47 UTC, merged