SSACSolver simulates the telegraph model incorrectly
StochSS/GillesPy2 pull request #918
Opened 2023-01-21 21:08 UTC by briandrawert

2023-01-26 13:56 UTC, BryanRumsey requested changes
Test notebook fails to run and should be moved to the Advanced_Features directory

2023-01-31 18:30 UTC, briandrawert commented
TODO: move telegraph model into example_models, make unit test, delete notebook

2023-02-09 18:34 UTC, seanebum approved these changes

2023-02-09 18:41 UTC, BryanRumsey approved these changes

2023-02-09 18:41 UTC, mdip226 approved these changes

2023-02-09 18:41 UTC, merged